server:
  port: 8088
  servlet:
    context-path: /bimcat

spring:
  datasource:
    url: jdbc:mysql://106.53.22.84:3306/shiro_test
    username: root
    password: 123456

#热部署
  devtools:
    remote:
      restart:
        enabled: true
        additional-paths: src/main/java

#开启驼峰命名规则
  mybatis:
    configuration:
      map-underscore-to-camel-case: true


#热更新的时候，页面也更新
  thymeleaf:
    cache: false
#多文件上传
  servlet:
    multipart:
      enabled: true

